#!/usr/bin/env node
const express = require("express");

const PORT = process.argv[2] || 3000;

const app = express();

app.disable("x-powered-by");

app.use((req, res, next) => {
	//let qString = Object.keys(req.query).map(k => `${k}=${req.query[k]}`).join("&");
	//if (qString !== "") qString = "?" + qString;

	//console.log(`${req.method} ${req.url}${qString}`);
	console.log(`${req.method} ${req.url}`);

	res.setHeader("Cache-Control", "no-cache");
	res.setHeader("Access-Control-Allow-Origin", "*");

	next();
});

app.use(express.static(__dirname));

app.listen(PORT, () => console.log(`Server listening on port ${PORT}`));
