#!/usr/bin/env node

const getQotd = require("./getQotd");
const { promisify } = require("util");

const redisClient = require("redis").createClient();
// const getAsync = promisify(redisClient.get).bind(redisClient); // set async function for redis
const setAsync = promisify(redisClient.set).bind(redisClient);

(async () => {
	// let qotdFromRedis = await getAsync("schoop:qotd");
	// if (qotdFromRedis === null) {
	let data = await getQotd();
	await setAsync("schoop:qotd", JSON.stringify(data));
	// }
	process.exit(0);
	// return qotdToSend;
})();
